# The URL the site will be built for
base_url = "https://mefhigoseth.github.io"

title = "[^MefhigosetH^]"
author = "Victor Villarreal"
description = "Portfolio de Victor Villarreal"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "tabi"

taxonomies = [
    { name = "tags", feed = true},
]

[markdown.highlighting]
theme = "catppuccin-frappe"
style = "class"

[extra]
logo_image = ""
twitter_handle = "MefhigosetH"

menu = [
    { url = "/", name = "Inicio", trailing_slash = false },
    { url = "projects", name = "Proyectos", trailing_slash = true },
]

socials = [
    { url = "https://github.com/mefhigoseth", name = "GitHub", icon = "github" },
    { url = "https://www.linkedin.com/in/vvillarreal1983/", name = "LinkedIn", icon = "linkedin" },
    { url = "https://www.youtube.com/@VictorVillarreal", name = "Youtube", icon = "youtube" },
    { url = "https://twitter.com/mefhigoseth", name = "Twitter", icon = "twitter" },
    { url = "https://mefhigoseth.blogspot.com/", name = "Old Blogger", icon = "google" },
]
